# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bbc_dict?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&rewriteBatchedStatements=TRUE
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456